### ISSUE TITLE
 AttributeError: 'module' object has no attribute 'initialize_mask'

### ISSUE THREAD

**Issue by gloria766** [pism/regional-tools#6]
When I was trying to run the PISM User’s Manual:  Example: A regional model of the Jakobshavn outlet glacier in Greenland and run the Python script to extract the areas, I encountered the following problems: 

lenovo@gf:~/pism/share/pism/examples/jako$ python pism_regional.py
Traceback (most recent call last):
  File "pism_regional.py", line 480, in <module>
    a = App(root)
  File "pism_regional.py", line 197, in __init__
    self.load_data()
  File "pism_regional.py", line 211, in load_data
    self.mask = initialize_mask(self.thk, self.x, self.y, None)
  File "pism_regional.py", line 125, in initialize_mask
    mask = dbg.initialize_mask(thk)
AttributeError: 'module' object has no attribute 'initialize_mask'

How can I solve this problem? Thank you for your comments!

**Comment by aaschwanden** [comment]
Can you please tell us which python version you are using?

We will look into this, but I currently don't have the correct modules installed.

**Comment by gloria766** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Thank you very much for your prompt reply. I used Python 2.7.16 on linux19.10. In addition, python3 is installed on my system and I don't know if it will affect the reading of scripts or modules.
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                837269296
                            
                    
                        
                            
                                    837269296@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 11/21/2019 11:09，Andy Aschwanden<notifications@github.com> wrote： 


Can you please tell us which python version you are using?
We will look into this, but I currently don't have the correct modules installed.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by aaschwanden** [comment]
Hi,

I don't have python 2 installed on my system anymore.

However, we must have forgotten to update the regional-tools to make them compatible with python 3. I'll update the code and then see if I can reproduce your problem.

**Comment by gloria766** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Ok, Thank you very much for your help.We look forward to solving this problem with your help and guidance.Thank you again
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                837269296
                            
                    
                        
                            
                                    837269296@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 11/21/2019 11:18，Andy Aschwanden<notifications@github.com> wrote： 


Hi,
I don't have python 2 installed on my system anymore.
However, we must have forgotten to update the regional-tools to make them compatible with python 3. I'll update the code and then see if I can reproduce your problem.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by aaschwanden** [comment]
@gloria766 : I've updated the code and made some changes. Could you try again?

**Comment by gloria766** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Dear Professor:
        OK!Thank you for your help.I'll try to run it with your modified code.  If there is any result or any problem, I will feedback to you.Can you tell me whether the modified code runs in Python2 or Python3?
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                837269296
                            
                    
                        
                            
                                    837269296@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 11/23/2019 05:42，Andy Aschwanden<notifications@github.com> wrote： 


@gloria766 : I've updated the code and made some changes. Could you try again?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by gloria766** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
     Dear Professor: Thank you very much for your help. The problem has been solved.I have successfully completed running the pism_regional.py script with Python2 .7.
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                837269296
                            
                    
                        
                            
                                    837269296@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 11/23/2019 09:40，837269296<837269296@qq.com> wrote： 




    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Dear Professor:
        OK!Thank you for your help.I'll try to run it with your modified code.  If there is any result or any problem, I will feedback to you.Can you tell me whether the modified code runs in Python2 or Python3?
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                837269296
                            
                    
                        
                            
                                    837269296@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 11/23/2019 05:42，Andy Aschwanden<notifications@github.com> wrote： 


@gloria766 : I've updated the code and made some changes. Could you try again?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
